name: MicroPython CI

on:
  push:
  pull_request:

jobs:

  build-esp32:
    runs-on: ubuntu-24.04
    name: Build esp32 port
    continue-on-error: true
    steps:
    - uses: ammaraskar/gcc-problem-matcher@master
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev parallel libfreetype-dev librlottie-dev libavformat-dev libavcodec-dev libswscale-dev libavutil-dev doxygen
        python3.10 -m pip install pycparser
    - name: Clone lv_micropython
      run: |
        git clone https://github.com/lvgl/lv_micropython.git .
        git checkout master
    - name: Initialize lv_bindings submodule
      run: git submodule update --init --recursive lib/lv_bindings
    - name: Update ${{ matrix.port }} port submodules
      run: make -C ports/esp32 DEBUG=1 USER_C_MODULES=../../lib/lv_bindings/bindings.cmake submodules
    - name: Checkout LVGL submodule
      working-directory: ./lib/lv_bindings/lvgl
      run: |
        git fetch --force ${{ github.event.repository.html_url }} "+refs/heads/*:refs/remotes/origin/*"
        git fetch --force ${{ github.event.repository.html_url }} "+refs/pull/*:refs/remotes/origin/pr/*"
        git checkout ${{ github.sha }} || git checkout ${{ github.event.pull_request.head.sha }}
        git submodule update --init --recursive
    - name: Build mpy-cross
      run: make -j $(nproc) -C mpy-cross
    - name: Override builtin python version
      run: sudo update-alternatives --install /usr/bin/python3 python3 $(which python3) 1
    - name: Setup ESP-IDF
      run: |
        source tools/ci.sh && ci_esp32_idf44_setup
    - name: Build ESP32 port
      run: |
        source tools/ci.sh && ci_esp32_build
    - name: Install requirements for the test
      run: |
        python3 -m pip install pillow
        mkdir lib/lv_bindings/lvgl/tests/micropy_test/artifacts
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts
        path: lib/lv_bindings/lvgl/tests/micropy_test/artifacts
